### ISSUE TITLE
Libraries built with this preset don't work in Astro

### ISSUE THREAD

**Issue by elite174** [amoutonbrady/rollup-preset-solid#13]
I tried to build my simple library with this plugin. The config for this was simple enough:

```
withSolid({
    input: "src/index.ts",
    targets: ["esm", "cjs"]
})
```

The first issue I discovered was the line with "solid" in package.json:
```
"exports": {
    ".": {
      "solid": "./dist/source/my-lib.jsx",
      ...
    }
  }
```
I got the following error:
```
Failed to resolve entry for package "my-package". The package may have incorrect main/module/exports specified in its package.json.
```

So I needed to remove line with "solid" from the exports and the issue disappeared.
Then I tried to use my lib with SPA (vite) and everything worked. However when I tried to use it with Astro, I got the following error:
```
> astro dev

   astro  v2.1.9 started in 111ms
  
  ┃ Local    http://127.0.0.1:3000/
  ┃ Network  use --host to expose
  
15:15:39 [vite] Error when evaluating SSR module /@fs/D:/Projects/test/packages/my-package/dist/esm/index.js:

15:15:39 [vite] Error when evaluating SSR module /src/examples/Horizontal.tsx:

15:15:39 [vite] Error when evaluating SSR module D:\Projects\test\apps\website\src\pages\index.astro:

 error   __vite_ssr_import_0__.template is not a function
  File:
    D:\Projects\test\src\constants.ts:398:28
  Stacktrace:
TypeError: __vite_ssr_import_0__.template is not a function
    at ../../src/constants.ts:398:28
    at async instantiateModule (file:///D:/Projects/test/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53996:9)

 error   __vite_ssr_import_0__.template is not a function
  File:
    D:\Projects\test\apps\website\D:\Projects\test\src\constants.ts:398:28
  Stacktrace:
TypeError: __vite_ssr_import_0__.template is not a function
    at ../../src/constants.ts:398:28
    at async instantiateModule (file:///D:/Projects/test/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53996:9)
```

**Comment by elite174** [comment]
Ok, I found that I need to add `solidOptions: { generate: "ssr", hydratable: true },` to build options to make it work in astro, however now it doesn't hydrate on the client. How to make it work?..

**Comment by elite174** [comment]
As I understood, I need to generate two outputs:

1) for web (I guess, esm might be enough)
2) for server with `solidOptions: { generate: "ssr", hydratable: true }` (esm, cjs)
3) Update `package.json` with
```
"exports: {
   ".": {
        "node": "server path",
        "browser": "browser path",
        "import": "browser path",
        "require": "server path"
        // "solid": "???" - this line breaks everything
   }
}"
```

So I needed smth like this:

```
withSolid([
  {
      input: "src/index.ts",
      targets: ["esm"]
  },
  {
      input: "src/index.ts",
      targets: ["esm", "cjs"],
      solidOptions: { generate: "ssr", hydratable: true }
  },
])
```

How to get a good folder structure in this case? When I try to do this, it builds everything into dist/index without splitting to esm, cjs folders.

**Comment by elite174** [comment]
My issue was the pnpm-lock file.
